name: Push ECR
on: [push]

jobs:

  pushToECR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Logging to ECR
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/openearthfoundation
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        VERSION: ${{ github.sha }}
        IMAGE: public.ecr.aws/openearthfoundation/helloworld
    - name: Pushing service to ECR
      run: |
        docker build -t $IMAGE:$VERSION helloworld
        docker tag $IMAGE:$VERSION $IMAGE:latest
        docker push $IMAGE:$VERSION
        docker push $IMAGE:latest
