name: Push ECR
on: [push]

jobs:

  pushToECR:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2.3.4

    - name: Logging in to ECR
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/openearthfoundation
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Building Docker image
      env:
        VERSION: ${{ github.sha }}
        IMAGE: public.ecr.aws/openearthfoundation/helloworld
      run: |
        echo "Building Docker image $IMAGE version $VERSION"
        docker build -t $IMAGE:$VERSION helloworld
        docker tag $IMAGE:$VERSION $IMAGE:latest

    - name: Pushing Docker image
      env:
        VERSION: ${{ github.sha }}
        IMAGE: public.ecr.aws/openearthfoundation/helloworld
      run: |
        echo "Pushing Docker image $IMAGE version $VERSION"
        docker push $IMAGE:$VERSION
        docker push $IMAGE:latest
