name: Push ECR EKS
on: [push]

jobs:

  pushToECR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Logging to ECR
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/openearthfoundation
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Pushing service to ECR
      run: |
        VERSION=1.0
        docker build -t helloworld:$VERSION helloworld
        docker tag helloworld:$VERSION public.ecr.aws/openearthfoundation/helloworld:$VERSION
        docker push public.ecr.aws/openearthfoundation/helloworld:$VERSION
